name: black&pylint

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11"]
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Python dependencies
      run: |
        python -m pip install requirements.txt
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pylint
        pip black==21.7b0
    - name: Analysing the code with pylint
      run: |
        black --diff --check $(git ls-files '*.py')
        pylint $(git ls-files '*.py')
        
